### ISSUE TITLE
Exception when running compile,clean,compile

### ISSUE THREAD

**Issue by lpiepiora** [sbt/sbt-avro#47]
When having SBT running in an interactive mode, running compile for the first time works just fine, but when doing compile, then clean, then compile again it fails with the following exception.

```
[info] Avro compiler using stringType=CharSequence
[info] Compiling Avro schema /Users/lpiepiora/xxx/src/main/avro/xxx.avsc
[info] Updating {file:/Users/lpiepiora/xxx/}xxx...
[info] Done updating.
[error] org.apache.avro.SchemaParseException: Can't redefine: X
[error]         at org.apache.avro.Schema$Names.put(Schema.java:1128)
[error]         at org.apache.avro.Schema$Names.add(Schema.java:1123)
[error]         at org.apache.avro.Schema.parse(Schema.java:1253)
[error]         at org.apache.avro.Schema$Parser.parse(Schema.java:1032)
[error]         at org.apache.avro.Schema$Parser.parse(Schema.java:997)
[error]         at sbtavro.SbtAvro$.compileAvsc(SbtAvro.scala:76)
[error]         at sbtavro.SbtAvro$.$anonfun$compile$4(SbtAvro.scala:103)
[error]         at sbtavro.SbtAvro$.$anonfun$compile$4$adapted(SbtAvro.scala:101)
[error]         at scala.collection.LinearSeqOptimized.foreach(LinearSeqOptimized.scala:71)
[error]         at scala.collection.LinearSeqOptimized.foreach$(LinearSeqOptimized.scala:68)
[error]         at scala.collection.mutable.MutableList.foreach(MutableList.scala:30)
[error]         at sbtavro.SbtAvro$.compile(SbtAvro.scala:101)
[error]         at sbtavro.SbtAvro$.$anonfun$sourceGeneratorTask$2(SbtAvro.scala:123)
[error]         at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error]         at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:293)
[error]         at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error]         at sbt.util.Difference.apply(Tracked.scala:313)
[error]         at sbt.util.Difference.apply(Tracked.scala:288)
[error]         at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error]         at sbtavro.SbtAvro$.$anonfun$sourceGeneratorTask$1(SbtAvro.scala:125)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (avro:generate) org.apache.avro.SchemaParseException: Can't redefine: X
[error] Total time: 2 s, completed 15-Sep-2017 16:14:42
```

**Comment by andybryant** [comment]
Looks like the plugin creates a single AvroParser in the SbtAvro companion object and reuses it between calls. The parser keeps a list of schemas it's seen and fails if you try and define the same schema twice.

We're getting a similar error trying to generate sources in two independent submodules.

Haven't tested at all to see if it causes other issues, but this should be resolved if SbtAvro.compileAvsc created a new parser each time.

**Comment by babatunde-abdulquddus** [comment]
@andybryant  you just saved my life :100:  :+1:

**Comment by Vrolijkx** [comment]
This issue still persists with ```compileAvsc``` because [the parser](https://github.com/sbt/sbt-avro/blob/4f0b83466beeaec7749c807e5a54322e6ef61d11/src/main/scala/sbtavro/SbtAvro.scala#L73) is still a singleton. Internally  here models are added to a static map and if added multiple times an exception is thrown like

```
org.apache.avro.SchemaParseException: Can't redefine: your.model
  at org.apache.avro.Schema$Names.put(Schema.java:1128)
  ....
```

**Comment by melodious** [comment]
The proposed solution - to create the parser each time breaks the ability to re-use schema parts. Any other solution?

**Comment by Vrolijkx** [comment]
Maybe reset the Schema to a new instance on the clean task. Don't know how easy this is in SBT plugins.

**Comment by brabster** [comment]
I'm having problems with this too, specifically in sbt shell. If I try to regenerate my schemas, I get the "can't redefine..." exception. My workaround is to `reload` before `avro:generate`, but it's a pain. I like the sound of @Vrolijkx's solution - `clean` was the first thing I tried.

**Comment by drorasaf** [comment]
This is fixed in #63, already an available tag includes it: 1.1.6
